// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNn2yk_K-cRp3hOS30EDwCpXQnS0JpWTw',
    appId: '1:527064373173:web:9d7016ad610573b33cebfc',
    messagingSenderId: '527064373173',
    projectId: 'achievelt-c0678',
    authDomain: 'achievelt-c0678.firebaseapp.com',
    storageBucket: 'achievelt-c0678.firebasestorage.app',
    measurementId: 'G-EPC54XJEYC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFHoh7uBDFNvfrGTl9Gi05JE2544gQi2E',
    appId: '1:527064373173:android:4565ab905227e64d3cebfc',
    messagingSenderId: '527064373173',
    projectId: 'achievelt-c0678',
    storageBucket: 'achievelt-c0678.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEfCj5LlNF_cX4qgHxGB6dxEiP5DrKc-I',
    appId: '1:527064373173:ios:492974663cf170ac3cebfc',
    messagingSenderId: '527064373173',
    projectId: 'achievelt-c0678',
    storageBucket: 'achievelt-c0678.firebasestorage.app',
    iosBundleId: 'com.example.acheiveIt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEfCj5LlNF_cX4qgHxGB6dxEiP5DrKc-I',
    appId: '1:527064373173:ios:492974663cf170ac3cebfc',
    messagingSenderId: '527064373173',
    projectId: 'achievelt-c0678',
    storageBucket: 'achievelt-c0678.firebasestorage.app',
    iosBundleId: 'com.example.acheiveIt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNn2yk_K-cRp3hOS30EDwCpXQnS0JpWTw',
    appId: '1:527064373173:web:27df844cca2397103cebfc',
    messagingSenderId: '527064373173',
    projectId: 'achievelt-c0678',
    authDomain: 'achievelt-c0678.firebaseapp.com',
    storageBucket: 'achievelt-c0678.firebasestorage.app',
    measurementId: 'G-XJDQ6EJTG6',
  );
}
