// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTPZ8LHdT8vUav1jrRQX0jHqLtM_QAmKg',
    appId: '1:324525075142:web:0dfaeb63fbbda431a585c7',
    messagingSenderId: '324525075142',
    projectId: 'acheive-it-947f9',
    authDomain: 'acheive-it-947f9.firebaseapp.com',
    storageBucket: 'acheive-it-947f9.firebasestorage.app',
    measurementId: 'G-KJ8RFJGBHS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0juUid1nf5W4OrclZNhey6y5ijWbGhQM',
    appId: '1:324525075142:android:294b620112cc085da585c7',
    messagingSenderId: '324525075142',
    projectId: 'acheive-it-947f9',
    storageBucket: 'acheive-it-947f9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvcirzmyeMI4niAkhEKEyhkD8juYkfqtQ',
    appId: '1:324525075142:ios:1ce16c1e5a4b1eaca585c7',
    messagingSenderId: '324525075142',
    projectId: 'acheive-it-947f9',
    storageBucket: 'acheive-it-947f9.firebasestorage.app',
    iosBundleId: 'com.example.acheiveIt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvcirzmyeMI4niAkhEKEyhkD8juYkfqtQ',
    appId: '1:324525075142:ios:1ce16c1e5a4b1eaca585c7',
    messagingSenderId: '324525075142',
    projectId: 'acheive-it-947f9',
    storageBucket: 'acheive-it-947f9.firebasestorage.app',
    iosBundleId: 'com.example.acheiveIt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTPZ8LHdT8vUav1jrRQX0jHqLtM_QAmKg',
    appId: '1:324525075142:web:c202a9730a84685aa585c7',
    messagingSenderId: '324525075142',
    projectId: 'acheive-it-947f9',
    authDomain: 'acheive-it-947f9.firebaseapp.com',
    storageBucket: 'acheive-it-947f9.firebasestorage.app',
    measurementId: 'G-FQ4H25T598',
  );
}
